### ISSUE TITLE
Test getBook

### ISSUE THREAD

**Issue by Eivyses** [Eivyses/E-Library#7]
Test if getBook REST method is working as intended, make sure it returns all necessary variables and information from server

**Comment by eivysess** [comment]
There's a bug with getting specific record, record loses half of it's description in UI.
Reproduction: Simply get a single book from list.

**Comment by Eivyses** [comment]
Bug source found and fixed, proceed with testing

**Comment by eivysess** [comment]
Testing of get done, closing issue
